/*
 * File: app/view/MyViewportViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.MyViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.myviewport',

    onGridpanelItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.ComponentQuery.query('#election_tabs')[0].enable();
        var recordData = record.data;
        recordData.start = new Date(recordData.electionStartDate);
        recordData.end = new Date(recordData.electionEndDate);
        recordData.start_time = new Date(recordData.electionStartDate);
        recordData.end_time = new Date(recordData.electionEndDate);

        Ext.ComponentQuery.query('#election_details')[0].getForm().setValues(recordData);


    },

    onDatefieldAfterRender: function(component, eOpts) {
        component.setMinValue(new Date());
        //HH = component;
    },

    onDatefieldSelect: function(field, value, eOpts) {
        field.nextSibling().enable();
        field.nextSibling().setMinValue(value);
    }

});
