/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'Admin.view.MyViewportViewModel',
        'Admin.view.MyViewportViewController',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.form.Panel',
        'Ext.form.trigger.Trigger',
        'Ext.toolbar.Fill',
        'Ext.XTemplate',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.grid.column.Number',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Widget',
        'Ext.toolbar.Paging'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    activeItem: 1,
    height: 250,
    width: 400,
    layout: 'card',

    items: [
        {
            xtype: 'panel',
            layout: 'center',
            bodyStyle: 'background:#f1f1f1;',
            items: [
                {
                    xtype: 'panel',
                    height: 404,
                    width: 470,
                    bodyStyle: 'background:transparent;',
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 92,
                            width: 113,
                            src: 'resources/images/logo.png'
                        },
                        {
                            xtype: 'label',
                            html: 'BLOCK CHAIN EVOTING SYSTEM',
                            style: 'font-size:20px;font-weight:600;color:#ff8f14;'
                        },
                        {
                            xtype: 'form',
                            height: 254,
                            margin: 20,
                            style: 'box-shadow: 0 10px 20px rgba(0,0,0,0.05), 0 6px 6px rgba(0,0,0,0.01);border-radius:5px;',
                            width: 419,
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: 10,
                                    width: '90%',
                                    fieldLabel: 'Login Id',
                                    labelAlign: 'top',
                                    labelStyle: 'font-weight:bold;color:grey;',
                                    name: 'username',
                                    fieldStyle: 'border-radius:5px;',
                                    allowBlank: false,
                                    triggers: {
                                        mytrigger: {
                                            cls: 'x-fa fa-user'
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 10 10 10',
                                    width: '90%',
                                    fieldLabel: 'Password',
                                    labelAlign: 'top',
                                    labelStyle: 'font-weight:bold;color:grey;',
                                    name: 'password',
                                    fieldStyle: 'border-radius:5px;',
                                    inputType: 'password',
                                    allowBlank: false,
                                    triggers: {
                                        mytrigger: {
                                            cls: 'x-fa fa-lock'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var form = button.up('form').getForm();
                                        if(form.isValid()){

                                            axios.post('http://localhost:4050/auth/login',form.getValues()).then(response=>{
                                                console.log(response);
                                                const {data} = response;

                                                if(data){
                                                    if(data.success){
                                                        var name_holder =Ext.ComponentQuery.query('#name_holder')[0];
                                                        name_holder.setData({
                                                            name:data.data.name,
                                                            telno:data.data.telno
                                                        });
                                                        button.up('myviewport').setActiveItem(1);
                                                        Ext.getStore('ElectionsStore').load();
                                                    }else{
                                                        Ext.Msg.alert('Error',data.error);
                                                    }
                                                }else{
                                                    Ext.Msg.alert('Error','Unable to login at this Time');
                                                }
                                            }).catch(error=>{
                                                console.log(error);
                                            });

                                        }else{
                                            Ext.toast('Enter all required fields');
                                        }
                                    },
                                    height: 44,
                                    margin: '5 10 20 10',
                                    style: 'background:#0f273c;border-radius:5px;',
                                    width: 356,
                                    text: '<b>LOGIN</b>'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'border',
            bodyStyle: 'background:#f1f1f1;',
            title: '',
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    activeItem: 2,
                    layout: 'card',
                    bodyPadding: 20,
                    bodyStyle: 'background:transparent;',
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            height: 54,
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'name_holder',
                                    tpl: [
                                        '<b><span>{name}</span></b><br>{telno}'
                                    ],
                                    width: 151
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            ui: 'light',
                            layout: 'border',
                            bodyStyle: 'background:transparent;',
                            title: 'Elections',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'west',
                                    split: true,
                                    width: 390,
                                    title: '',
                                    store: 'ElectionsStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            dataIndex: 'string',
                                            text: '#'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 120,
                                            dataIndex: 'electionName',
                                            text: 'Election Name'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            flex: 1,
                                            width: 133,
                                            dataIndex: 'electionStartDate',
                                            text: 'Start Date'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            width: 41,
                                            iconCls: 'x-fa fa-eye-slash orange'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            width: 41,
                                            iconCls: 'x-fa fa-trash red'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        var panel = Ext.widget('newelection',{
                                                            modal:true,
                                                            floating:true,
                                                            closable:true,
                                                            autoShow:true
                                                        });
                                                    },
                                                    iconCls: 'x-fa fa-plus',
                                                    text: 'Create New Election'
                                                }
                                            ]
                                        }
                                    ],
                                    listeners: {
                                        itemclick: 'onGridpanelItemClick'
                                    }
                                },
                                {
                                    xtype: 'tabpanel',
                                    region: 'center',
                                    disabled: true,
                                    itemId: 'election_tabs',
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Election Details',
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    itemId: 'election_details',
                                                    width: 466,
                                                    bodyPadding: 10,
                                                    title: '',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Name',
                                                            name: 'electionName',
                                                            allowBlank: false
                                                        },
                                                        {
                                                            xtype: 'textareafield',
                                                            fieldLabel: 'Description',
                                                            name: 'electionDescription',
                                                            allowBlank: false
                                                        },
                                                        {
                                                            xtype: 'datefield',
                                                            fieldLabel: 'Start  Date',
                                                            name: 'start',
                                                            allowBlank: false,
                                                            format: 'd-m-y',
                                                            listeners: {
                                                                afterrender: 'onDatefieldAfterRender',
                                                                select: 'onDatefieldSelect'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'datefield',
                                                            disabled: true,
                                                            fieldLabel: 'End  Date',
                                                            name: 'end',
                                                            allowBlank: false,
                                                            format: 'd-m-y'
                                                        },
                                                        {
                                                            xtype: 'timefield',
                                                            flex: 1,
                                                            itemId: 'start_time',
                                                            fieldLabel: 'Start Time',
                                                            name: 'start_time',
                                                            allowBlank: false
                                                        },
                                                        {
                                                            xtype: 'timefield',
                                                            flex: 1,
                                                            itemId: 'end_time',
                                                            fieldLabel: 'End Time',
                                                            name: 'end_time',
                                                            allowBlank: false
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, e) {
                                                                var form = button.up('form').getForm();

                                                                function formatter(date, time){
                                                                    var newFormat = `${date.split('-')[1]}-${date.split('-')[0]}-${date.split('-')[2]}`;
                                                                    var dateObj = new Date(newFormat);

                                                                    dateObj =  new Date(dateObj.setHours(time.hours));
                                                                    dateObj = new Date(dateObj.setMinutes(time.minutes));
                                                                    return dateObj.toISOString();

                                                                }
                                                                if(form.isValid()){
                                                                    var data = form.getValues();
                                                                    start_time = button.up('newelection').down('#start_time').getValue();
                                                                    var end_time = button.up('newelection').down('#end_time').getValue();


                                                                    data.electionStartDate = formatter(data.start,{
                                                                        hours:start_time.getHours(),
                                                                        minutes:start_time.getMinutes()
                                                                    });
                                                                    data.electionEndDate  = formatter(data.end,{
                                                                        hours:end_time.getHours(),
                                                                        minutes:end_time.getMinutes()
                                                                    });
                                                                    delete data.start;
                                                                    delete data.end;
                                                                    delete data.start_time;
                                                                    delete data.end_time;

                                                                    axios.post(`${config.ADMIN_API}/election-instances`,data).then(response=>{
                                                                    console.log(response);
                                                                    let {data, status} = response;
                                                                    if(data&& status==200){

                                                                        Ext.toast('Election Created !!!');
                                                                        button.up('form').close();
                                                                        Ext.getStore('ElectionsStore').load();

                                                                    }else{
                                                                        Ext.Msg.alert('Error','Unable to create Election');
                                                                    }

                                                                }).catch(error=>{
                                                                    console.log(error);
                                                                });


                                                            }else{
                                                                Ext.toast('Please Enter All Required Fields');
                                                            }
                                                            },
                                                            height: 45,
                                                            style: 'border-radius:4px;',
                                                            text: 'Save Changes'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            layout: 'fit',
                                            title: 'Positions',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'string',
                                                            text: 'String'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            dataIndex: 'number',
                                                            text: 'Number'
                                                        },
                                                        {
                                                            xtype: 'datecolumn',
                                                            dataIndex: 'date',
                                                            text: 'Date'
                                                        },
                                                        {
                                                            xtype: 'booleancolumn',
                                                            dataIndex: 'bool',
                                                            text: 'Boolean'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Polling Stations'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            ui: 'light',
                            layout: 'border',
                            title: 'Registry',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    ui: 'light',
                                    title: 'Register Voters',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'String'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Boolean'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    region: 'west',
                                    split: true,
                                    width: 320,
                                    title: '',
                                    store: 'RegisterStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            dataIndex: 'string',
                                            text: '#'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            width: 190,
                                            dataIndex: 'registerName',
                                            text: 'Name'
                                        },
                                        {
                                            xtype: 'widgetcolumn',
                                            width: 48,
                                            text: '',
                                            widget: {
                                                xtype: 'button',
                                                ui: 'plain-toolbar-small',
                                                iconCls: 'x-fa fa-edit',
                                                text: ''
                                            }
                                        },
                                        {
                                            xtype: 'widgetcolumn',
                                            width: 51,
                                            text: '',
                                            widget: {
                                                xtype: 'button',
                                                ui: 'plain-toolbar-small',
                                                iconCls: 'x-fa fa-trash',
                                                text: ''
                                            }
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        var panel = Ext.widget('newregister',{
                                                            modal:true,
                                                            floating:true,
                                                            closable:true,
                                                            autoShow:true
                                                        });
                                                    },
                                                    width: 162,
                                                    iconCls: 'x-fa fa-plus',
                                                    text: '<b>Create Register</b>'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            ui: 'light',
                            title: 'Users',
                            store: 'UserStore',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    dataIndex: 'string',
                                    text: 'String'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'firstName',
                                    text: 'First Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'otherNames',
                                    text: 'Other Names'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'username',
                                    text: 'Username'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'gender',
                                    text: 'Gender'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'smsmTelno',
                                    text: 'Telno'
                                },
                                {
                                    xtype: 'widgetcolumn',
                                    width: 61,
                                    text: '',
                                    widget: {
                                        xtype: 'button',
                                        ui: 'plain-toolbar-small',
                                        iconCls: 'x-fa fa-edit'
                                    }
                                },
                                {
                                    xtype: 'widgetcolumn',
                                    width: 61,
                                    text: '',
                                    widget: {
                                        xtype: 'button',
                                        ui: 'plain-toolbar-small',
                                        iconCls: 'x-fa fa-trash'
                                    }
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var panel = Ext.widget('newuser',{
                                                    modal:true,
                                                    floating:true,
                                                    closable:true,
                                                    autoShow:true
                                                });
                                            },
                                            iconCls: 'x-fa fa-user',
                                            text: 'Create User'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    width: 206,
                    bodyStyle: 'background:#0f273c',
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 54,
                            style: 'background:white',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'image',
                                    height: 38,
                                    width: 39,
                                    src: 'resources/images/logo.png'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    html: 'BLOCK CHAIN EVOTING SYSTEM',
                                    style: 'font-weight:bold;color:orange;'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            height: 120,
                            style: 'background:transparent;border:0px;border-bottom:1px solid rgba(255,255,255,0.1)',
                            iconAlign: 'top',
                            iconCls: 'x-fa fa-edit fa-2x',
                            text: '<br>ELECTIONS'
                        },
                        {
                            xtype: 'button',
                            height: 120,
                            style: 'background:transparent;border:0px;border-bottom:1px solid rgba(255,255,255,0.1)',
                            iconAlign: 'top',
                            iconCls: 'x-fa fa-file fa-2x',
                            text: '<br>REGISTRY'
                        },
                        {
                            xtype: 'button',
                            height: 120,
                            style: 'background:transparent;border:0px;border-bottom:1px solid rgba(255,255,255,0.1)',
                            iconAlign: 'top',
                            iconCls: 'x-fa fa-home fa-2x',
                            text: '<br>POLLING STATIONS'
                        },
                        {
                            xtype: 'button',
                            height: 120,
                            style: 'background:transparent;border:0px;border-bottom:1px solid rgba(255,255,255,0.1)',
                            iconAlign: 'top',
                            iconCls: 'x-fa fa-users fa-2x',
                            text: '<br>USERS'
                        }
                    ]
                }
            ]
        }
    ]

});