/*
 * File: app/view/NewRegister.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Admin.view.NewRegister', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newregister',

    requires: [
        'Admin.view.NewElectionViewModel1',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'newregister'
    },
    width: 466,
    bodyPadding: 10,
    title: 'New Register',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'textfield',
            fieldLabel: 'Name',
            name: 'registerName',
            allowBlank: false
        },
        {
            xtype: 'textareafield',
            fieldLabel: 'Description',
            name: 'registerDescription',
            allowBlank: false
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                var form = button.up('form').getForm();


                if(form.isValid()){
                    var data = form.getValues();

                    axios.post(`${config.ADMIN_API}/voter-registers`,data).then(response=>{
                    console.log(response);
                    let {data, status} = response;
                    if(data&& status==200){

                        Ext.toast('Register Created !!!');
                        button.up('form').close();
                        Ext.getStore('RegisterStore').load();

                    }else{
                        Ext.Msg.alert('Error','Unable to create Register');
                    }

                }).catch(error=>{
                    Ext.Msg.alert('Error','Unable to create User');
                });


            }else{
                Ext.toast('Please Enter All Required Fields');
            }
            },
            height: 45,
            style: 'border-radius:4px;',
            text: 'Add Register'
        }
    ]

});